import { Mail, MessageSquare, CreditCard, Shield, Webhook, Star } from "lucide-react";
import { SiTwilio, SiStripe, SiPaypal, SiGoogle, SiGithub, SiSlack, SiDiscord, SiTelegram, SiWhatsapp, SiLinkedin } from "react-icons/si";

export interface IntegrationField {
  key: string;
  label: string;
  labelAr: string;
  type: "text" | "password" | "email";
  placeholder: string;
  required: boolean;
}

export interface IntegrationProvider {
  key: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  icon: any;
  iconColor: string;
  url: string;
  costRating: 1 | 2 | 3 | 4 | 5;
  qualityRating: 1 | 2 | 3 | 4 | 5;
  pricingNote?: string;
  pricingNoteAr?: string;
  fields: IntegrationField[];
  category: "email" | "sms" | "payments" | "auth" | "webhooks";
}

export const emailProviders: IntegrationProvider[] = [
  {
    key: "sendgrid",
    name: "SendGrid",
    nameAr: "SendGrid",
    description: "Cloud-based email delivery service",
    descriptionAr: "خدمة إرسال البريد السحابية",
    icon: Mail,
    iconColor: "text-blue-500",
    url: "https://sendgrid.com",
    costRating: 4,
    qualityRating: 5,
    pricingNote: "Free: 100/day, From $19.95/mo",
    pricingNoteAr: "مجاني: 100/يوم، من 19.95$/شهر",
    category: "email",
    fields: [
      { key: "SENDGRID_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "SG.xxxx", required: true },
      { key: "SENDGRID_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@example.com", required: true },
      { key: "SENDGRID_FROM_NAME", label: "From Name", labelAr: "اسم المرسل", type: "text", placeholder: "My App", required: false },
    ],
  },
  {
    key: "mailgun",
    name: "Mailgun",
    nameAr: "Mailgun",
    description: "Powerful transactional email APIs",
    descriptionAr: "واجهات برمجة قوية للبريد الإلكتروني",
    icon: Mail,
    iconColor: "text-red-600",
    url: "https://mailgun.com",
    costRating: 4,
    qualityRating: 5,
    pricingNote: "Free: 5,000/3 months, From $35/mo",
    pricingNoteAr: "مجاني: 5,000/3 أشهر، من 35$/شهر",
    category: "email",
    fields: [
      { key: "MAILGUN_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "key-xxxx", required: true },
      { key: "MAILGUN_DOMAIN", label: "Domain", labelAr: "النطاق", type: "text", placeholder: "mg.example.com", required: true },
      { key: "MAILGUN_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@mg.example.com", required: true },
    ],
  },
  {
    key: "smtp",
    name: "SMTP Server",
    nameAr: "خادم SMTP",
    description: "Custom SMTP server configuration",
    descriptionAr: "تكوين خادم SMTP مخصص",
    icon: Mail,
    iconColor: "text-gray-600",
    url: "",
    costRating: 5,
    qualityRating: 4,
    pricingNote: "Free with most providers",
    pricingNoteAr: "مجاني مع معظم المزودين",
    category: "email",
    fields: [
      { key: "SMTP_HOST", label: "Host", labelAr: "الخادم", type: "text", placeholder: "smtp.example.com", required: true },
      { key: "SMTP_PORT", label: "Port", labelAr: "المنفذ", type: "text", placeholder: "587", required: true },
      { key: "SMTP_USER", label: "Username", labelAr: "اسم المستخدم", type: "text", placeholder: "user@example.com", required: true },
      { key: "SMTP_PASSWORD", label: "Password", labelAr: "كلمة المرور", type: "password", placeholder: "••••••••", required: true },
      { key: "SMTP_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@example.com", required: true },
    ],
  },
  {
    key: "postmark",
    name: "Postmark",
    nameAr: "Postmark",
    description: "Fast and reliable email delivery",
    descriptionAr: "تسليم بريد سريع وموثوق",
    icon: Mail,
    iconColor: "text-yellow-500",
    url: "https://postmarkapp.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "Free: 100/mo, From $15/mo",
    pricingNoteAr: "مجاني: 100/شهر، من 15$/شهر",
    category: "email",
    fields: [
      { key: "POSTMARK_API_KEY", label: "Server Token", labelAr: "رمز الخادم", type: "password", placeholder: "xxxx-xxxx-xxxx", required: true },
      { key: "POSTMARK_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@example.com", required: true },
    ],
  },
  {
    key: "resend",
    name: "Resend",
    nameAr: "Resend",
    description: "Modern email API for developers",
    descriptionAr: "واجهة بريد حديثة للمطورين",
    icon: Mail,
    iconColor: "text-foreground",
    url: "https://resend.com",
    costRating: 4,
    qualityRating: 5,
    pricingNote: "Free: 3,000/mo, From $20/mo",
    pricingNoteAr: "مجاني: 3,000/شهر، من 20$/شهر",
    category: "email",
    fields: [
      { key: "RESEND_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "re_xxxx", required: true },
      { key: "RESEND_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@example.com", required: true },
    ],
  },
  {
    key: "amazon_ses",
    name: "Amazon SES",
    nameAr: "Amazon SES",
    description: "Scalable email service by AWS",
    descriptionAr: "خدمة بريد قابلة للتوسع من AWS",
    icon: Mail,
    iconColor: "text-orange-500",
    url: "https://aws.amazon.com/ses",
    costRating: 5,
    qualityRating: 5,
    pricingNote: "$0.10 per 1,000 emails",
    pricingNoteAr: "0.10$ لكل 1,000 بريد",
    category: "email",
    fields: [
      { key: "AWS_ACCESS_KEY_ID", label: "Access Key ID", labelAr: "معرف مفتاح الوصول", type: "password", placeholder: "AKIAXXXX", required: true },
      { key: "AWS_SECRET_ACCESS_KEY", label: "Secret Access Key", labelAr: "مفتاح الوصول السري", type: "password", placeholder: "••••••••", required: true },
      { key: "AWS_REGION", label: "Region", labelAr: "المنطقة", type: "text", placeholder: "us-east-1", required: true },
      { key: "SES_FROM_EMAIL", label: "From Email", labelAr: "البريد المرسل", type: "email", placeholder: "noreply@example.com", required: true },
    ],
  },
];

export const smsProviders: IntegrationProvider[] = [
  {
    key: "twilio",
    name: "Twilio",
    nameAr: "Twilio",
    description: "Global SMS and messaging platform",
    descriptionAr: "منصة رسائل SMS عالمية",
    icon: SiTwilio,
    iconColor: "text-red-500",
    url: "https://www.twilio.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "From $0.0079/message",
    pricingNoteAr: "من 0.0079$/رسالة",
    category: "sms",
    fields: [
      { key: "TWILIO_ACCOUNT_SID", label: "Account SID", labelAr: "معرف الحساب", type: "text", placeholder: "ACxxxx", required: true },
      { key: "TWILIO_AUTH_TOKEN", label: "Auth Token", labelAr: "رمز المصادقة", type: "password", placeholder: "••••••••", required: true },
      { key: "TWILIO_PHONE_NUMBER", label: "Phone Number", labelAr: "رقم الهاتف", type: "text", placeholder: "+1234567890", required: true },
    ],
  },
  {
    key: "messagebird",
    name: "MessageBird",
    nameAr: "MessageBird",
    description: "Omnichannel messaging platform",
    descriptionAr: "منصة رسائل متعددة القنوات",
    icon: MessageSquare,
    iconColor: "text-blue-600",
    url: "https://messagebird.com",
    costRating: 3,
    qualityRating: 4,
    pricingNote: "From €0.0065/message",
    pricingNoteAr: "من 0.0065€/رسالة",
    category: "sms",
    fields: [
      { key: "MESSAGEBIRD_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "xxxx", required: true },
      { key: "MESSAGEBIRD_ORIGINATOR", label: "Originator", labelAr: "المرسل", type: "text", placeholder: "MyApp", required: true },
    ],
  },
  {
    key: "vonage",
    name: "Vonage",
    nameAr: "Vonage",
    description: "Communications APIs platform",
    descriptionAr: "منصة واجهات الاتصالات",
    icon: MessageSquare,
    iconColor: "text-purple-600",
    url: "https://www.vonage.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "From $0.0068/message",
    pricingNoteAr: "من 0.0068$/رسالة",
    category: "sms",
    fields: [
      { key: "VONAGE_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "text", placeholder: "xxxx", required: true },
      { key: "VONAGE_API_SECRET", label: "API Secret", labelAr: "سر API", type: "password", placeholder: "••••••••", required: true },
      { key: "VONAGE_FROM", label: "From Number", labelAr: "رقم المرسل", type: "text", placeholder: "+1234567890", required: true },
    ],
  },
  {
    key: "plivo",
    name: "Plivo",
    nameAr: "Plivo",
    description: "Cloud communications platform",
    descriptionAr: "منصة اتصالات سحابية",
    icon: MessageSquare,
    iconColor: "text-green-500",
    url: "https://www.plivo.com",
    costRating: 4,
    qualityRating: 4,
    pricingNote: "From $0.0050/message",
    pricingNoteAr: "من 0.0050$/رسالة",
    category: "sms",
    fields: [
      { key: "PLIVO_AUTH_ID", label: "Auth ID", labelAr: "معرف المصادقة", type: "text", placeholder: "xxxx", required: true },
      { key: "PLIVO_AUTH_TOKEN", label: "Auth Token", labelAr: "رمز المصادقة", type: "password", placeholder: "••••••••", required: true },
      { key: "PLIVO_PHONE_NUMBER", label: "Phone Number", labelAr: "رقم الهاتف", type: "text", placeholder: "+1234567890", required: true },
    ],
  },
  {
    key: "clicksend",
    name: "ClickSend",
    nameAr: "ClickSend",
    description: "Business communication platform",
    descriptionAr: "منصة اتصالات الأعمال",
    icon: MessageSquare,
    iconColor: "text-cyan-500",
    url: "https://www.clicksend.com",
    costRating: 4,
    qualityRating: 4,
    pricingNote: "From $0.0255/message",
    pricingNoteAr: "من 0.0255$/رسالة",
    category: "sms",
    fields: [
      { key: "CLICKSEND_USERNAME", label: "Username", labelAr: "اسم المستخدم", type: "text", placeholder: "user@example.com", required: true },
      { key: "CLICKSEND_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "xxxx", required: true },
    ],
  },
  {
    key: "unifonic",
    name: "Unifonic",
    nameAr: "يونيفونك",
    description: "Middle East focused messaging",
    descriptionAr: "منصة رسائل للشرق الأوسط",
    icon: MessageSquare,
    iconColor: "text-green-600",
    url: "https://www.unifonic.com",
    costRating: 3,
    qualityRating: 4,
    pricingNote: "Custom pricing for MENA",
    pricingNoteAr: "تسعير مخصص للشرق الأوسط",
    category: "sms",
    fields: [
      { key: "UNIFONIC_APP_SID", label: "App SID", labelAr: "معرف التطبيق", type: "text", placeholder: "xxxx", required: true },
      { key: "UNIFONIC_SENDER_ID", label: "Sender ID", labelAr: "معرف المرسل", type: "text", placeholder: "MyApp", required: true },
    ],
  },
  {
    key: "mobily",
    name: "Mobily",
    nameAr: "موبايلي",
    description: "Saudi Arabian SMS provider",
    descriptionAr: "مزود رسائل سعودي",
    icon: MessageSquare,
    iconColor: "text-purple-500",
    url: "https://www.mobily.com.sa",
    costRating: 4,
    qualityRating: 4,
    pricingNote: "Competitive Saudi rates",
    pricingNoteAr: "أسعار سعودية تنافسية",
    category: "sms",
    fields: [
      { key: "MOBILY_USERNAME", label: "Username", labelAr: "اسم المستخدم", type: "text", placeholder: "user", required: true },
      { key: "MOBILY_PASSWORD", label: "Password", labelAr: "كلمة المرور", type: "password", placeholder: "••••••••", required: true },
      { key: "MOBILY_SENDER", label: "Sender Name", labelAr: "اسم المرسل", type: "text", placeholder: "MyApp", required: true },
    ],
  },
];

export const paymentProviders: IntegrationProvider[] = [
  {
    key: "stripe",
    name: "Stripe",
    nameAr: "Stripe",
    description: "Global payment processing",
    descriptionAr: "معالجة مدفوعات عالمية",
    icon: SiStripe,
    iconColor: "text-purple-500",
    url: "https://stripe.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "2.9% + $0.30",
    pricingNoteAr: "2.9% + 0.30$",
    category: "payments",
    fields: [
      { key: "STRIPE_SECRET_KEY", label: "Secret Key", labelAr: "المفتاح السري", type: "password", placeholder: "sk_xxxx", required: true },
      { key: "STRIPE_PUBLISHABLE_KEY", label: "Publishable Key", labelAr: "المفتاح العام", type: "text", placeholder: "pk_xxxx", required: true },
      { key: "STRIPE_WEBHOOK_SECRET", label: "Webhook Secret", labelAr: "سر Webhook", type: "password", placeholder: "whsec_xxxx", required: false },
    ],
  },
  {
    key: "paypal",
    name: "PayPal",
    nameAr: "PayPal",
    description: "Global payment platform",
    descriptionAr: "منصة مدفوعات عالمية",
    icon: SiPaypal,
    iconColor: "text-blue-600",
    url: "https://www.paypal.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "2.9% + $0.30",
    pricingNoteAr: "2.9% + 0.30$",
    category: "payments",
    fields: [
      { key: "PAYPAL_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "xxxx", required: true },
      { key: "PAYPAL_CLIENT_SECRET", label: "Client Secret", labelAr: "سر العميل", type: "password", placeholder: "••••••••", required: true },
      { key: "PAYPAL_MODE", label: "Mode", labelAr: "الوضع", type: "text", placeholder: "sandbox or live", required: true },
    ],
  },
  {
    key: "tap",
    name: "Tap Payments",
    nameAr: "تاب للمدفوعات",
    description: "MENA payment gateway",
    descriptionAr: "بوابة دفع للشرق الأوسط",
    icon: CreditCard,
    iconColor: "text-cyan-500",
    url: "https://www.tap.company",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "2.5% + 1 SAR",
    pricingNoteAr: "2.5% + 1 ريال",
    category: "payments",
    fields: [
      { key: "TAP_SECRET_KEY", label: "Secret Key", labelAr: "المفتاح السري", type: "password", placeholder: "sk_xxxx", required: true },
      { key: "TAP_PUBLISHABLE_KEY", label: "Publishable Key", labelAr: "المفتاح العام", type: "text", placeholder: "pk_xxxx", required: true },
    ],
  },
  {
    key: "moyasar",
    name: "Moyasar",
    nameAr: "مُيسّر",
    description: "Saudi payment gateway",
    descriptionAr: "بوابة دفع سعودية",
    icon: CreditCard,
    iconColor: "text-green-600",
    url: "https://moyasar.com",
    costRating: 4,
    qualityRating: 5,
    pricingNote: "2%, Mada 1.5%",
    pricingNoteAr: "2%، مدى 1.5%",
    category: "payments",
    fields: [
      { key: "MOYASAR_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "sk_xxxx", required: true },
      { key: "MOYASAR_PUBLISHABLE_KEY", label: "Publishable Key", labelAr: "المفتاح العام", type: "text", placeholder: "pk_xxxx", required: true },
    ],
  },
  {
    key: "paymob",
    name: "Paymob",
    nameAr: "باي موب",
    description: "Egypt payment gateway",
    descriptionAr: "بوابة دفع مصرية",
    icon: CreditCard,
    iconColor: "text-orange-500",
    url: "https://paymob.com",
    costRating: 4,
    qualityRating: 4,
    pricingNote: "2.5%",
    pricingNoteAr: "2.5%",
    category: "payments",
    fields: [
      { key: "PAYMOB_API_KEY", label: "API Key", labelAr: "مفتاح API", type: "password", placeholder: "xxxx", required: true },
      { key: "PAYMOB_INTEGRATION_ID", label: "Integration ID", labelAr: "معرف التكامل", type: "text", placeholder: "xxxx", required: true },
      { key: "PAYMOB_IFRAME_ID", label: "iFrame ID", labelAr: "معرف iFrame", type: "text", placeholder: "xxxx", required: true },
    ],
  },
  {
    key: "hyperpay",
    name: "HyperPay",
    nameAr: "هايبر باي",
    description: "MENA enterprise payments",
    descriptionAr: "مدفوعات مؤسسية للشرق الأوسط",
    icon: CreditCard,
    iconColor: "text-indigo-500",
    url: "https://www.hyperpay.com",
    costRating: 3,
    qualityRating: 5,
    pricingNote: "Custom pricing",
    pricingNoteAr: "تسعير مخصص",
    category: "payments",
    fields: [
      { key: "HYPERPAY_ENTITY_ID", label: "Entity ID", labelAr: "معرف الكيان", type: "text", placeholder: "xxxx", required: true },
      { key: "HYPERPAY_ACCESS_TOKEN", label: "Access Token", labelAr: "رمز الوصول", type: "password", placeholder: "••••••••", required: true },
    ],
  },
  {
    key: "razorpay",
    name: "Razorpay",
    nameAr: "رازورباي",
    description: "India payment gateway",
    descriptionAr: "بوابة دفع هندية",
    icon: CreditCard,
    iconColor: "text-blue-700",
    url: "https://razorpay.com",
    costRating: 4,
    qualityRating: 5,
    pricingNote: "2%",
    pricingNoteAr: "2%",
    category: "payments",
    fields: [
      { key: "RAZORPAY_KEY_ID", label: "Key ID", labelAr: "معرف المفتاح", type: "text", placeholder: "rzp_xxxx", required: true },
      { key: "RAZORPAY_KEY_SECRET", label: "Key Secret", labelAr: "سر المفتاح", type: "password", placeholder: "••••••••", required: true },
    ],
  },
];

export const authProviders: IntegrationProvider[] = [
  {
    key: "google_oauth",
    name: "Google OAuth",
    nameAr: "مصادقة Google",
    description: "Sign in with Google",
    descriptionAr: "تسجيل الدخول بـ Google",
    icon: SiGoogle,
    iconColor: "text-red-500",
    url: "https://console.cloud.google.com",
    costRating: 5,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "GOOGLE_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "xxxx.apps.googleusercontent.com", required: true },
      { key: "GOOGLE_CLIENT_SECRET", label: "Client Secret", labelAr: "سر العميل", type: "password", placeholder: "••••••••", required: true },
    ],
  },
  {
    key: "microsoft_oauth",
    name: "Microsoft Azure AD",
    nameAr: "مصادقة Microsoft",
    description: "Sign in with Microsoft",
    descriptionAr: "تسجيل الدخول بـ Microsoft",
    icon: Shield,
    iconColor: "text-blue-600",
    url: "https://portal.azure.com",
    costRating: 4,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "AZURE_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "xxxx", required: true },
      { key: "AZURE_CLIENT_SECRET", label: "Client Secret", labelAr: "سر العميل", type: "password", placeholder: "••••••••", required: true },
      { key: "AZURE_TENANT_ID", label: "Tenant ID", labelAr: "معرف المستأجر", type: "text", placeholder: "xxxx", required: true },
    ],
  },
  {
    key: "apple_signin",
    name: "Apple Sign In",
    nameAr: "تسجيل الدخول بـ Apple",
    description: "Sign in with Apple",
    descriptionAr: "تسجيل الدخول بـ Apple",
    icon: Shield,
    iconColor: "text-foreground",
    url: "https://developer.apple.com",
    costRating: 4,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "APPLE_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "com.example.app", required: true },
      { key: "APPLE_TEAM_ID", label: "Team ID", labelAr: "معرف الفريق", type: "text", placeholder: "xxxx", required: true },
      { key: "APPLE_KEY_ID", label: "Key ID", labelAr: "معرف المفتاح", type: "text", placeholder: "xxxx", required: true },
      { key: "APPLE_PRIVATE_KEY", label: "Private Key", labelAr: "المفتاح الخاص", type: "password", placeholder: "-----BEGIN PRIVATE KEY-----", required: true },
    ],
  },
  {
    key: "github_oauth",
    name: "GitHub OAuth",
    nameAr: "مصادقة GitHub",
    description: "Sign in with GitHub",
    descriptionAr: "تسجيل الدخول بـ GitHub",
    icon: SiGithub,
    iconColor: "text-foreground",
    url: "https://github.com",
    costRating: 5,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "GITHUB_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "xxxx", required: true },
      { key: "GITHUB_CLIENT_SECRET", label: "Client Secret", labelAr: "سر العميل", type: "password", placeholder: "••••••••", required: true },
    ],
  },
  {
    key: "linkedin_oauth",
    name: "LinkedIn OAuth",
    nameAr: "مصادقة LinkedIn",
    description: "Sign in with LinkedIn",
    descriptionAr: "تسجيل الدخول بـ LinkedIn",
    icon: SiLinkedin,
    iconColor: "text-blue-700",
    url: "https://www.linkedin.com/developers",
    costRating: 5,
    qualityRating: 4,
    category: "auth",
    fields: [
      { key: "LINKEDIN_CLIENT_ID", label: "Client ID", labelAr: "معرف العميل", type: "text", placeholder: "xxxx", required: true },
      { key: "LINKEDIN_CLIENT_SECRET", label: "Client Secret", labelAr: "سر العميل", type: "password", placeholder: "••••••••", required: true },
    ],
  },
  {
    key: "saml_sso",
    name: "SAML SSO",
    nameAr: "SAML SSO",
    description: "Enterprise SSO with SAML",
    descriptionAr: "تسجيل دخول مؤسسي بـ SAML",
    icon: Shield,
    iconColor: "text-indigo-600",
    url: "https://www.okta.com",
    costRating: 2,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "SAML_ENTRY_POINT", label: "Entry Point", labelAr: "نقطة الدخول", type: "text", placeholder: "https://idp.example.com/sso", required: true },
      { key: "SAML_ISSUER", label: "Issuer", labelAr: "المُصدر", type: "text", placeholder: "https://app.example.com", required: true },
      { key: "SAML_CERTIFICATE", label: "Certificate", labelAr: "الشهادة", type: "password", placeholder: "-----BEGIN CERTIFICATE-----", required: true },
    ],
  },
  {
    key: "ldap",
    name: "LDAP / Active Directory",
    nameAr: "LDAP / Active Directory",
    description: "Enterprise directory integration",
    descriptionAr: "تكامل دليل المؤسسات",
    icon: Shield,
    iconColor: "text-green-700",
    url: "",
    costRating: 4,
    qualityRating: 5,
    category: "auth",
    fields: [
      { key: "LDAP_URL", label: "LDAP URL", labelAr: "رابط LDAP", type: "text", placeholder: "ldap://ldap.example.com:389", required: true },
      { key: "LDAP_BIND_DN", label: "Bind DN", labelAr: "DN الربط", type: "text", placeholder: "cn=admin,dc=example,dc=com", required: true },
      { key: "LDAP_BIND_PASSWORD", label: "Bind Password", labelAr: "كلمة مرور الربط", type: "password", placeholder: "••••••••", required: true },
      { key: "LDAP_SEARCH_BASE", label: "Search Base", labelAr: "قاعدة البحث", type: "text", placeholder: "ou=users,dc=example,dc=com", required: true },
    ],
  },
];

export const webhookProviders: IntegrationProvider[] = [
  {
    key: "custom_webhook",
    name: "Custom Webhooks",
    nameAr: "Webhooks مخصصة",
    description: "Send events to custom endpoints",
    descriptionAr: "إرسال الأحداث لنقاط نهاية مخصصة",
    icon: Webhook,
    iconColor: "text-green-500",
    url: "https://webhook.site",
    costRating: 5,
    qualityRating: 4,
    category: "webhooks",
    fields: [
      { key: "WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://example.com/webhook", required: true },
      { key: "WEBHOOK_SECRET", label: "Secret", labelAr: "السر", type: "password", placeholder: "••••••••", required: false },
    ],
  },
  {
    key: "zapier",
    name: "Zapier",
    nameAr: "Zapier",
    description: "Automation platform",
    descriptionAr: "منصة أتمتة",
    icon: Webhook,
    iconColor: "text-orange-500",
    url: "https://zapier.com",
    costRating: 2,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "ZAPIER_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://hooks.zapier.com/xxxx", required: true },
    ],
  },
  {
    key: "make",
    name: "Make",
    nameAr: "Make",
    description: "Visual automation platform",
    descriptionAr: "منصة أتمتة مرئية",
    icon: Webhook,
    iconColor: "text-purple-500",
    url: "https://www.make.com",
    costRating: 3,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "MAKE_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://hook.make.com/xxxx", required: true },
    ],
  },
  {
    key: "n8n",
    name: "n8n",
    nameAr: "n8n",
    description: "Open-source automation",
    descriptionAr: "أتمتة مفتوحة المصدر",
    icon: Webhook,
    iconColor: "text-red-500",
    url: "https://n8n.io",
    costRating: 5,
    qualityRating: 4,
    category: "webhooks",
    fields: [
      { key: "N8N_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://n8n.example.com/webhook/xxxx", required: true },
    ],
  },
  {
    key: "slack",
    name: "Slack",
    nameAr: "Slack",
    description: "Team messaging platform",
    descriptionAr: "منصة رسائل الفريق",
    icon: SiSlack,
    iconColor: "text-purple-600",
    url: "https://slack.com",
    costRating: 4,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "SLACK_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://hooks.slack.com/services/xxxx", required: true },
      { key: "SLACK_BOT_TOKEN", label: "Bot Token", labelAr: "رمز البوت", type: "password", placeholder: "xoxb-xxxx", required: false },
    ],
  },
  {
    key: "teams",
    name: "Microsoft Teams",
    nameAr: "Microsoft Teams",
    description: "Enterprise collaboration",
    descriptionAr: "تعاون المؤسسات",
    icon: MessageSquare,
    iconColor: "text-blue-600",
    url: "https://teams.microsoft.com",
    costRating: 4,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "TEAMS_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://outlook.office.com/webhook/xxxx", required: true },
    ],
  },
  {
    key: "discord",
    name: "Discord",
    nameAr: "Discord",
    description: "Community messaging",
    descriptionAr: "رسائل المجتمع",
    icon: SiDiscord,
    iconColor: "text-indigo-500",
    url: "https://discord.com",
    costRating: 5,
    qualityRating: 4,
    category: "webhooks",
    fields: [
      { key: "DISCORD_WEBHOOK_URL", label: "Webhook URL", labelAr: "رابط Webhook", type: "text", placeholder: "https://discord.com/api/webhooks/xxxx", required: true },
    ],
  },
  {
    key: "telegram",
    name: "Telegram Bot",
    nameAr: "بوت Telegram",
    description: "Telegram notifications",
    descriptionAr: "إشعارات Telegram",
    icon: SiTelegram,
    iconColor: "text-blue-400",
    url: "https://telegram.org",
    costRating: 5,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "TELEGRAM_BOT_TOKEN", label: "Bot Token", labelAr: "رمز البوت", type: "password", placeholder: "xxxx:xxxx", required: true },
      { key: "TELEGRAM_CHAT_ID", label: "Chat ID", labelAr: "معرف المحادثة", type: "text", placeholder: "-123456789", required: true },
    ],
  },
  {
    key: "whatsapp",
    name: "WhatsApp Business",
    nameAr: "WhatsApp Business",
    description: "WhatsApp notifications",
    descriptionAr: "إشعارات WhatsApp",
    icon: SiWhatsapp,
    iconColor: "text-green-500",
    url: "https://business.whatsapp.com",
    costRating: 2,
    qualityRating: 5,
    category: "webhooks",
    fields: [
      { key: "WHATSAPP_PHONE_NUMBER_ID", label: "Phone Number ID", labelAr: "معرف رقم الهاتف", type: "text", placeholder: "xxxx", required: true },
      { key: "WHATSAPP_ACCESS_TOKEN", label: "Access Token", labelAr: "رمز الوصول", type: "password", placeholder: "••••••••", required: true },
    ],
  },
];

export const allProviders = {
  email: emailProviders,
  sms: smsProviders,
  payments: paymentProviders,
  auth: authProviders,
  webhooks: webhookProviders,
};

export function getProviderByKey(key: string): IntegrationProvider | undefined {
  for (const category of Object.values(allProviders)) {
    const provider = category.find(p => p.key === key);
    if (provider) return provider;
  }
  return undefined;
}
