/**
 * Failure Recovery Panel | لوحة إدارة الفشل والتعافي
 */

import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Progress } from "@/components/ui/progress";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { 
  AlertTriangle, Shield, Activity, Clock, CheckCircle, XCircle,
  Play, Calendar, RefreshCw, Server, Database, Network, Lock,
  Zap, GitBranch, AlertCircle, TrendingUp, FileWarning
} from "lucide-react";

interface FailureScenario {
  id: string;
  category: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  severity: string;
  probability: number;
  impact: number;
  riskScore: number;
  triggers: string[];
  symptoms: string[];
  affectedComponents: string[];
  status: string;
  autoGenerated: boolean;
}

interface RecoveryPlan {
  id: string;
  scenarioId: string;
  name: string;
  nameAr: string;
  priority: number;
  estimatedRecoveryTime: number;
  steps: { id: string; action: string; actionAr: string; type: string; completed: boolean }[];
  status: string;
  autoExecute: boolean;
  lastTestedAt?: string;
  successRate: number;
}

interface EmergencyTest {
  id: string;
  planId: string;
  name: string;
  nameAr: string;
  status: string;
  scheduledAt?: string;
  completedAt?: string;
  overallScore: number;
  findings: string[];
  recommendations: string[];
}

interface Incident {
  id: string;
  title: string;
  titleAr: string;
  severity: string;
  status: string;
  detectedAt: string;
  resolvedAt?: string;
  affectedServices: string[];
}

interface HealthStatus {
  component: string;
  status: string;
  lastCheck: string;
  metrics: Record<string, number>;
  issues: string[];
}

interface Stats {
  totalScenarios: number;
  scenariosByCategory: Record<string, number>;
  scenariosBySeverity: Record<string, number>;
  totalPlans: number;
  totalTests: number;
  averageTestScore: number;
  activeIncidents: number;
  resolvedIncidents: number;
  healthyComponents: number;
  totalComponents: number;
}

const categoryIcons: Record<string, any> = {
  database: Database,
  infrastructure: Server,
  network: Network,
  security: Lock,
  application: Zap,
  integration: GitBranch,
  performance: TrendingUp
};

const severityColors: Record<string, string> = {
  critical: "bg-red-500/10 text-red-500 border-red-500/20",
  high: "bg-orange-500/10 text-orange-500 border-orange-500/20",
  medium: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
  low: "bg-green-500/10 text-green-500 border-green-500/20"
};

const statusColors: Record<string, string> = {
  healthy: "bg-green-500/10 text-green-500",
  degraded: "bg-yellow-500/10 text-yellow-500",
  unhealthy: "bg-red-500/10 text-red-500",
  unknown: "bg-muted text-muted-foreground"
};

export function FailureRecoveryPanel() {
  const [activeTab, setActiveTab] = useState("overview");
  const [selectedScenario, setSelectedScenario] = useState<string | null>(null);

  const { data: statsData, isLoading: statsLoading } = useQuery<{ data: Stats }>({
    queryKey: ["/api/failure-recovery/stats"]
  });

  const { data: scenariosData, isLoading: scenariosLoading } = useQuery<{ data: FailureScenario[] }>({
    queryKey: ["/api/failure-recovery/scenarios"]
  });

  const { data: plansData } = useQuery<{ data: RecoveryPlan[] }>({
    queryKey: ["/api/failure-recovery/plans"]
  });

  const { data: testsData } = useQuery<{ data: EmergencyTest[] }>({
    queryKey: ["/api/failure-recovery/tests"]
  });

  const { data: incidentsData } = useQuery<{ data: Incident[] }>({
    queryKey: ["/api/failure-recovery/incidents"]
  });

  const { data: healthData } = useQuery<{ data: HealthStatus[] }>({
    queryKey: ["/api/failure-recovery/health"]
  });

  const executePlanMutation = useMutation({
    mutationFn: (planId: string) => apiRequest("POST", `/api/failure-recovery/plans/${planId}/execute`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/failure-recovery/plans"] });
      queryClient.invalidateQueries({ queryKey: ["/api/failure-recovery/stats"] });
    }
  });

  const runTestMutation = useMutation({
    mutationFn: (testId: string) => apiRequest("POST", `/api/failure-recovery/tests/${testId}/run`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/failure-recovery/tests"] });
      queryClient.invalidateQueries({ queryKey: ["/api/failure-recovery/stats"] });
    }
  });

  const stats = statsData?.data;
  const scenarios = scenariosData?.data || [];
  const plans = plansData?.data || [];
  const tests = testsData?.data || [];
  const incidents = incidentsData?.data || [];
  const health = healthData?.data || [];

  if (statsLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <RefreshCw className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6" data-testid="failure-recovery-panel">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Failure Management & Recovery</h2>
          <p className="text-muted-foreground">إدارة الفشل والتعافي</p>
        </div>
        <Badge variant="outline" className="gap-1">
          <Shield className="w-3 h-3" />
          {stats?.totalScenarios || 0} Scenarios
        </Badge>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-blue-500/10">
                <FileWarning className="w-5 h-5 text-blue-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalScenarios || 0}</p>
                <p className="text-xs text-muted-foreground">Scenarios | سيناريوهات</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-green-500/10">
                <Shield className="w-5 h-5 text-green-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.totalPlans || 0}</p>
                <p className="text-xs text-muted-foreground">Recovery Plans | خطط التعافي</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-500/10">
                <Activity className="w-5 h-5 text-purple-500" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.averageTestScore || 0}%</p>
                <p className="text-xs text-muted-foreground">Test Score | نتيجة الاختبار</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${stats?.activeIncidents ? 'bg-red-500/10' : 'bg-green-500/10'}`}>
                <AlertTriangle className={`w-5 h-5 ${stats?.activeIncidents ? 'text-red-500' : 'text-green-500'}`} />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats?.activeIncidents || 0}</p>
                <p className="text-xs text-muted-foreground">Active Incidents | حوادث نشطة</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Health Status */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <Activity className="w-5 h-5" />
            System Health | صحة النظام
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-3">
            {health.map((h) => (
              <div
                key={h.component}
                className={`p-3 rounded-lg border ${statusColors[h.status]}`}
                data-testid={`health-${h.component}`}
              >
                <div className="flex items-center gap-2 mb-1">
                  {h.status === 'healthy' ? (
                    <CheckCircle className="w-4 h-4" />
                  ) : h.status === 'degraded' ? (
                    <AlertCircle className="w-4 h-4" />
                  ) : (
                    <XCircle className="w-4 h-4" />
                  )}
                  <span className="text-sm font-medium capitalize">{h.component}</span>
                </div>
                <p className="text-xs opacity-75">{h.metrics?.responseTime || 0}ms</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="overview" data-testid="tab-overview">
            Overview | نظرة عامة
          </TabsTrigger>
          <TabsTrigger value="scenarios" data-testid="tab-scenarios">
            Scenarios | السيناريوهات
          </TabsTrigger>
          <TabsTrigger value="plans" data-testid="tab-plans">
            Recovery Plans | خطط التعافي
          </TabsTrigger>
          <TabsTrigger value="tests" data-testid="tab-tests">
            Tests | الاختبارات
          </TabsTrigger>
          <TabsTrigger value="incidents" data-testid="tab-incidents">
            Incidents | الحوادث
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4">
          <div className="grid md:grid-cols-2 gap-6">
            {/* Risk Distribution */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Risk by Severity | المخاطر حسب الخطورة</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {Object.entries(stats?.scenariosBySeverity || {}).map(([severity, count]) => (
                  <div key={severity} className="flex items-center gap-3">
                    <Badge className={severityColors[severity]}>{severity}</Badge>
                    <Progress value={(count as number / (stats?.totalScenarios || 1)) * 100} className="flex-1" />
                    <span className="text-sm font-medium w-8">{count as number}</span>
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Category Distribution */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Scenarios by Category | السيناريوهات حسب الفئة</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {Object.entries(stats?.scenariosByCategory || {}).filter(([_, count]) => count > 0).map(([category, count]) => {
                  const Icon = categoryIcons[category] || AlertTriangle;
                  return (
                    <div key={category} className="flex items-center gap-3">
                      <div className="flex items-center gap-2 w-32">
                        <Icon className="w-4 h-4 text-muted-foreground" />
                        <span className="text-sm capitalize">{category}</span>
                      </div>
                      <Progress value={(count as number / (stats?.totalScenarios || 1)) * 100} className="flex-1" />
                      <span className="text-sm font-medium w-8">{count as number}</span>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="scenarios" className="mt-4">
          <ScrollArea className="h-[500px]">
            <div className="space-y-3">
              {scenarios.map((scenario) => {
                const Icon = categoryIcons[scenario.category] || AlertTriangle;
                return (
                  <Card 
                    key={scenario.id} 
                    className="cursor-pointer hover-elevate"
                    onClick={() => setSelectedScenario(selectedScenario === scenario.id ? null : scenario.id)}
                    data-testid={`scenario-${scenario.id}`}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex items-start gap-3">
                          <div className="p-2 rounded-lg bg-muted">
                            <Icon className="w-5 h-5" />
                          </div>
                          <div>
                            <h4 className="font-medium">{scenario.name}</h4>
                            <p className="text-sm text-muted-foreground">{scenario.nameAr}</p>
                            <p className="text-xs text-muted-foreground mt-1">{scenario.description}</p>
                          </div>
                        </div>
                        <div className="flex flex-col items-end gap-2">
                          <Badge className={severityColors[scenario.severity]}>{scenario.severity}</Badge>
                          <span className="text-xs text-muted-foreground">
                            Risk: {Math.round(scenario.riskScore * 100)}%
                          </span>
                        </div>
                      </div>

                      {selectedScenario === scenario.id && (
                        <div className="mt-4 pt-4 border-t space-y-3">
                          <div className="grid grid-cols-3 gap-4 text-sm">
                            <div>
                              <p className="text-muted-foreground">Probability | الاحتمالية</p>
                              <p className="font-medium">{Math.round(scenario.probability * 100)}%</p>
                            </div>
                            <div>
                              <p className="text-muted-foreground">Impact | التأثير</p>
                              <p className="font-medium">{Math.round(scenario.impact * 100)}%</p>
                            </div>
                            <div>
                              <p className="text-muted-foreground">Status | الحالة</p>
                              <Badge variant="outline">{scenario.status}</Badge>
                            </div>
                          </div>
                          <div>
                            <p className="text-sm text-muted-foreground mb-2">Triggers | المحفزات</p>
                            <div className="flex flex-wrap gap-1">
                              {scenario.triggers.map((t, i) => (
                                <Badge key={i} variant="secondary" className="text-xs">{t}</Badge>
                              ))}
                            </div>
                          </div>
                          <div>
                            <p className="text-sm text-muted-foreground mb-2">Affected Components | المكونات المتأثرة</p>
                            <div className="flex flex-wrap gap-1">
                              {scenario.affectedComponents.map((c, i) => (
                                <Badge key={i} variant="outline" className="text-xs">{c}</Badge>
                              ))}
                            </div>
                          </div>
                        </div>
                      )}
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="plans" className="mt-4">
          <ScrollArea className="h-[500px]">
            <div className="space-y-3">
              {plans.map((plan) => (
                <Card key={plan.id} data-testid={`plan-${plan.id}`}>
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <div className="flex items-center gap-2">
                          <h4 className="font-medium">{plan.name}</h4>
                          {plan.autoExecute && (
                            <Badge variant="secondary" className="text-xs">Auto-Execute</Badge>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground">{plan.nameAr}</p>
                        <div className="flex items-center gap-4 mt-2 text-xs text-muted-foreground">
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {plan.estimatedRecoveryTime} min
                          </span>
                          <span>{plan.steps.length} steps</span>
                          <span>Success: {Math.round(plan.successRate * 100)}%</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">Priority {plan.priority}</Badge>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              size="icon"
                              variant="ghost"
                              onClick={() => executePlanMutation.mutate(plan.id)}
                              disabled={executePlanMutation.isPending}
                              data-testid={`execute-plan-${plan.id}`}
                            >
                              <Play className="w-4 h-4" />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>Execute Plan | تنفيذ الخطة</TooltipContent>
                        </Tooltip>
                      </div>
                    </div>

                    <div className="mt-3 space-y-1">
                      {plan.steps.slice(0, 3).map((step) => (
                        <div key={step.id} className="flex items-center gap-2 text-sm">
                          {step.completed ? (
                            <CheckCircle className="w-3 h-3 text-green-500" />
                          ) : (
                            <div className="w-3 h-3 rounded-full border" />
                          )}
                          <span className={step.completed ? 'text-muted-foreground line-through' : ''}>
                            {step.action}
                          </span>
                          <Badge variant="outline" className="text-xs ml-auto">{step.type}</Badge>
                        </div>
                      ))}
                      {plan.steps.length > 3 && (
                        <p className="text-xs text-muted-foreground">+{plan.steps.length - 3} more steps</p>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="tests" className="mt-4">
          <ScrollArea className="h-[500px]">
            <div className="space-y-3">
              {tests.length === 0 ? (
                <Card>
                  <CardContent className="p-8 text-center">
                    <Calendar className="w-12 h-12 mx-auto text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">No emergency tests scheduled</p>
                    <p className="text-sm text-muted-foreground">لا توجد اختبارات طوارئ مجدولة</p>
                  </CardContent>
                </Card>
              ) : (
                tests.map((test) => (
                  <Card key={test.id} data-testid={`test-${test.id}`}>
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <h4 className="font-medium">{test.name}</h4>
                          <p className="text-sm text-muted-foreground">{test.nameAr}</p>
                          {test.scheduledAt && (
                            <p className="text-xs text-muted-foreground mt-1">
                              Scheduled: {new Date(test.scheduledAt).toLocaleString()}
                            </p>
                          )}
                        </div>
                        <div className="flex items-center gap-2">
                          <Badge className={test.status === 'passed' ? 'bg-green-500/10 text-green-500' : test.status === 'failed' ? 'bg-red-500/10 text-red-500' : 'bg-blue-500/10 text-blue-500'}>
                            {test.status}
                          </Badge>
                          {test.status === 'scheduled' && (
                            <Button
                              size="icon"
                              variant="ghost"
                              onClick={() => runTestMutation.mutate(test.id)}
                              disabled={runTestMutation.isPending}
                              data-testid={`run-test-${test.id}`}
                            >
                              <Play className="w-4 h-4" />
                            </Button>
                          )}
                        </div>
                      </div>

                      {test.completedAt && (
                        <div className="mt-3 pt-3 border-t">
                          <div className="flex items-center gap-4">
                            <div>
                              <p className="text-sm text-muted-foreground">Score</p>
                              <p className="text-2xl font-bold">{test.overallScore}%</p>
                            </div>
                            <Progress value={test.overallScore} className="flex-1" />
                          </div>
                          {test.findings.length > 0 && (
                            <div className="mt-2">
                              <p className="text-xs text-muted-foreground mb-1">Findings:</p>
                              {test.findings.slice(0, 2).map((f, i) => (
                                <p key={i} className="text-xs">{f}</p>
                              ))}
                            </div>
                          )}
                        </div>
                      )}
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="incidents" className="mt-4">
          <ScrollArea className="h-[500px]">
            <div className="space-y-3">
              {incidents.length === 0 ? (
                <Card>
                  <CardContent className="p-8 text-center">
                    <CheckCircle className="w-12 h-12 mx-auto text-green-500 mb-4" />
                    <p className="font-medium">No Active Incidents</p>
                    <p className="text-sm text-muted-foreground">لا توجد حوادث نشطة</p>
                  </CardContent>
                </Card>
              ) : (
                incidents.map((incident) => (
                  <Card key={incident.id} data-testid={`incident-${incident.id}`}>
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <div className="flex items-center gap-2">
                            <AlertTriangle className={`w-4 h-4 ${incident.severity === 'critical' ? 'text-red-500' : incident.severity === 'high' ? 'text-orange-500' : 'text-yellow-500'}`} />
                            <h4 className="font-medium">{incident.title}</h4>
                          </div>
                          <p className="text-sm text-muted-foreground">{incident.titleAr}</p>
                          <p className="text-xs text-muted-foreground mt-1">
                            Detected: {new Date(incident.detectedAt).toLocaleString()}
                          </p>
                        </div>
                        <div className="flex flex-col items-end gap-2">
                          <Badge className={severityColors[incident.severity]}>{incident.severity}</Badge>
                          <Badge variant="outline">{incident.status}</Badge>
                        </div>
                      </div>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {incident.affectedServices.map((s, i) => (
                          <Badge key={i} variant="secondary" className="text-xs">{s}</Badge>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          </ScrollArea>
        </TabsContent>
      </Tabs>
    </div>
  );
}

export default FailureRecoveryPanel;
