/**
 * Frontend Generator - مولّد الفرونت إند
 * 
 * Generates React + Tailwind + Shadcn frontend code from Blueprint specifications.
 * Produces pages, components, forms, and layouts.
 */

import {
  Blueprint,
  FrontendSpec,
  DataModelSpec,
  EntityDefinition,
  PageDefinition,
  NavigationSpec,
  ThemeSpec,
  GeneratedFile
} from './types';

export class FrontendGenerator {
  
  /**
   * Generate all frontend files from a Blueprint
   */
  generateFrontendFiles(blueprint: Blueprint): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const { frontend, dataModel, auth } = blueprint;
    
    // Generate main App.tsx
    files.push(this.generateAppFile(frontend, blueprint.id));
    
    // Generate pages
    for (const page of frontend.pages) {
      files.push(this.generatePage(page, dataModel, blueprint.id));
    }
    
    // Generate entity components (tables, forms)
    for (const entity of dataModel.entities) {
      files.push(this.generateEntityTable(entity, blueprint.id));
      files.push(this.generateEntityForm(entity, blueprint.id));
    }
    
    // Generate sidebar component
    files.push(this.generateSidebar(frontend.navigation, blueprint.id));
    
    // Generate theme CSS variables
    files.push(this.generateThemeCSS(frontend.theme, blueprint.id));
    
    console.log(`[FrontendGenerator] Generated ${files.length} frontend files for blueprint ${blueprint.id}`);
    
    return files;
  }
  
  /**
   * Generate main App.tsx file
   */
  private generateAppFile(frontend: FrontendSpec, blueprintId: string): GeneratedFile {
    const pageImports = frontend.pages.map(p => 
      `const ${p.name} = lazy(() => import('./pages/${this.toKebabCase(p.name)}'));`
    ).join('\n');
    
    const routes = frontend.pages.map(p => 
      `        <Route path="${p.path}" component={${p.name}} />`
    ).join('\n');
    
    const content = `/**
 * Application Entry Point
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { lazy, Suspense } from 'react';
import { Switch, Route } from 'wouter';
import { QueryClientProvider } from '@tanstack/react-query';
import { queryClient } from './lib/queryClient';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { ThemeToggle } from '@/components/theme-toggle';
import { Loader2 } from 'lucide-react';

// Lazy load pages
${pageImports}

function LoadingFallback() {
  return (
    <div className="flex items-center justify-center h-full">
      <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
    </div>
  );
}

function Router() {
  return (
    <Suspense fallback={<LoadingFallback />}>
      <Switch>
${routes}
        <Route component={() => <div className="p-8 text-center">Page not found</div>} />
      </Switch>
    </Suspense>
  );
}

export default function App() {
  const style = {
    "--sidebar-width": "16rem",
    "--sidebar-width-icon": "3rem",
  };

  return (
    <QueryClientProvider client={queryClient}>
      <TooltipProvider>
        <SidebarProvider style={style as React.CSSProperties}>
          <div className="flex h-screen w-full">
            <AppSidebar />
            <div className="flex flex-col flex-1">
              <header className="flex items-center justify-between gap-4 p-2 border-b">
                <SidebarTrigger data-testid="button-sidebar-toggle" />
                <ThemeToggle />
              </header>
              <main className="flex-1 overflow-auto">
                <Router />
              </main>
            </div>
          </div>
        </SidebarProvider>
        <Toaster />
      </TooltipProvider>
    </QueryClientProvider>
  );
}
`;
    
    return {
      path: `generated/${blueprintId}/client/src/App.tsx`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Generate a page component
   */
  private generatePage(
    page: PageDefinition,
    dataModel: DataModelSpec,
    blueprintId: string
  ): GeneratedFile {
    const isListPage = page.name.endsWith('List');
    const isFormPage = page.name.endsWith('Form');
    const entityName = page.name.replace(/List$|Form$/, '');
    const entity = dataModel.entities.find(e => e.name === entityName);
    
    let content: string;
    
    if (isListPage && entity) {
      content = this.generateListPageContent(page, entity, blueprintId);
    } else if (isFormPage && entity) {
      content = this.generateFormPageContent(page, entity, blueprintId);
    } else if (page.name === 'Dashboard') {
      content = this.generateDashboardContent(page, dataModel, blueprintId);
    } else {
      content = this.generateGenericPageContent(page, blueprintId);
    }
    
    return {
      path: `generated/${blueprintId}/client/src/pages/${this.toKebabCase(page.name)}.tsx`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Generate list page content
   */
  private generateListPageContent(
    page: PageDefinition,
    entity: EntityDefinition,
    blueprintId: string
  ): string {
    return `/**
 * ${page.meta.title} Page - ${page.meta.titleAr}
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ${entity.name}Table } from '@/components/${this.toKebabCase(entity.name)}-table';
import { Plus, RefreshCw } from 'lucide-react';

export default function ${page.name}() {
  const [page, setPage] = useState(1);
  
  const { data, isLoading, refetch } = useQuery<{
    success: boolean;
    data: any[];
    pagination: { page: number; limit: number; total: number; pages: number };
  }>({
    queryKey: ['/api/${entity.tableName.replace(/_/g, '-')}', page]
  });

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold" data-testid="text-page-title">${entity.nameAr}</h1>
          <p className="text-muted-foreground">${page.meta.description}</p>
        </div>
        <div className="flex items-center gap-2">
          <Button 
            variant="outline" 
            size="icon"
            onClick={() => refetch()}
            data-testid="button-refresh"
          >
            <RefreshCw className="w-4 h-4" />
          </Button>
          <Link href="${page.path}/new">
            <Button data-testid="button-create">
              <Plus className="w-4 h-4 mr-2" />
              Add New
            </Button>
          </Link>
        </div>
      </div>
      
      <Card>
        <CardContent className="p-0">
          <${entity.name}Table 
            data={data?.data || []}
            loading={isLoading}
            pagination={data?.pagination}
            onPageChange={setPage}
          />
        </CardContent>
      </Card>
    </div>
  );
}
`;
  }
  
  /**
   * Generate form page content
   */
  private generateFormPageContent(
    page: PageDefinition,
    entity: EntityDefinition,
    blueprintId: string
  ): string {
    return `/**
 * ${page.meta.title} Page - ${page.meta.titleAr}
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { useParams, useLocation } from 'wouter';
import { useQuery, useMutation } from '@tanstack/react-query';
import { queryClient, apiRequest } from '@/lib/queryClient';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ${entity.name}Form } from '@/components/${this.toKebabCase(entity.name)}-form';
import { useToast } from '@/hooks/use-toast';
import { ArrowLeft, Save } from 'lucide-react';

export default function ${page.name}Page() {
  const { id } = useParams<{ id?: string }>();
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const isEdit = id && id !== 'new';
  
  const { data, isLoading } = useQuery<{ success: boolean; data: any }>({
    queryKey: ['/api/${entity.tableName.replace(/_/g, '-')}', id],
    enabled: !!isEdit
  });
  
  const mutation = useMutation({
    mutationFn: async (formData: any) => {
      if (isEdit) {
        return apiRequest(\`/api/${entity.tableName.replace(/_/g, '-')}/\${id}\`, {
          method: 'PUT',
          body: JSON.stringify(formData)
        });
      }
      return apiRequest('/api/${entity.tableName.replace(/_/g, '-')}', {
        method: 'POST',
        body: JSON.stringify(formData)
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['/api/${entity.tableName.replace(/_/g, '-')}'] });
      toast({ title: isEdit ? 'Updated' : 'Created', description: 'Record saved successfully' });
      setLocation('/${entity.tableName.replace(/_/g, '-')}');
    },
    onError: (error: any) => {
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    }
  });

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center gap-4">
        <Button 
          variant="ghost" 
          size="icon"
          onClick={() => setLocation('/${entity.tableName.replace(/_/g, '-')}')}
          data-testid="button-back"
        >
          <ArrowLeft className="w-4 h-4" />
        </Button>
        <div>
          <h1 className="text-2xl font-bold" data-testid="text-page-title">
            {isEdit ? 'Edit' : 'Create'} ${entity.nameAr}
          </h1>
        </div>
      </div>
      
      <Card className="max-w-2xl">
        <CardContent className="pt-6">
          <${entity.name}Form 
            defaultValues={isEdit ? data?.data : undefined}
            loading={isLoading || mutation.isPending}
            onSubmit={(data) => mutation.mutate(data)}
          />
        </CardContent>
      </Card>
    </div>
  );
}
`;
  }
  
  /**
   * Generate dashboard content
   */
  private generateDashboardContent(
    page: PageDefinition,
    dataModel: DataModelSpec,
    blueprintId: string
  ): string {
    const statCards = dataModel.entities.slice(0, 4).map((e, i) => `
        <Card key="${e.name}" data-testid="card-stat-${e.tableName}">
          <CardHeader className="flex flex-row items-center justify-between gap-4 pb-2">
            <CardTitle className="text-sm font-medium">${e.nameAr}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">--</div>
            <p className="text-xs text-muted-foreground">Total records</p>
          </CardContent>
        </Card>`
    ).join('\n');
    
    return `/**
 * Dashboard Page - لوحة التحكم
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { LayoutDashboard } from 'lucide-react';

export default function Dashboard() {
  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2" data-testid="text-page-title">
          <LayoutDashboard className="w-6 h-6" />
          لوحة التحكم
        </h1>
        <p className="text-muted-foreground">Overview of your platform activity</p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
${statCards}
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Recent Activity</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground text-center py-8">No recent activity</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-2 gap-2">
            {/* Quick action buttons will be rendered here */}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
`;
  }
  
  /**
   * Generate generic page content
   */
  private generateGenericPageContent(page: PageDefinition, blueprintId: string): string {
    return `/**
 * ${page.meta.title} Page - ${page.meta.titleAr}
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function ${page.name}() {
  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold" data-testid="text-page-title">${page.meta.titleAr}</h1>
        <p className="text-muted-foreground">${page.meta.description}</p>
      </div>
      
      <Card>
        <CardContent className="pt-6">
          <p className="text-muted-foreground text-center py-8">
            Content for ${page.meta.title}
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
`;
  }
  
  /**
   * Generate entity table component
   */
  private generateEntityTable(entity: EntityDefinition, blueprintId: string): GeneratedFile {
    const displayFields = entity.fields.filter(f => 
      !['id', 'createdAt', 'updatedAt', 'deletedAt', 'tenantId'].includes(f.name)
    ).slice(0, 5);
    
    const headers = displayFields.map(f => 
      `          <th className="text-left p-3 font-medium">${f.nameAr}</th>`
    ).join('\n');
    
    const cells = displayFields.map(f => 
      `            <td className="p-3">{item.${f.name}}</td>`
    ).join('\n');
    
    const content = `/**
 * ${entity.name} Table Component - جدول ${entity.nameAr}
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { Link } from 'wouter';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Edit, Trash2, Loader2 } from 'lucide-react';

interface ${entity.name}TableProps {
  data: any[];
  loading?: boolean;
  pagination?: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
  onPageChange?: (page: number) => void;
}

export function ${entity.name}Table({ data, loading, pagination, onPageChange }: ${entity.name}TableProps) {
  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </div>
    );
  }
  
  if (data.length === 0) {
    return (
      <div className="text-center py-12 text-muted-foreground">
        No records found
      </div>
    );
  }

  return (
    <div>
      <table className="w-full" data-testid="table-${entity.tableName}">
        <thead className="border-b bg-muted/50">
          <tr>
${headers}
            <th className="text-left p-3 font-medium w-24">Actions</th>
          </tr>
        </thead>
        <tbody>
          {data.map((item, index) => (
            <tr key={item.id || index} className="border-b hover-elevate" data-testid={\`row-${entity.tableName}-\${item.id || index}\`}>
${cells}
              <td className="p-3">
                <div className="flex items-center gap-1">
                  <Link href={\`/${entity.tableName.replace(/_/g, '-')}/\${item.id}\`}>
                    <Button size="icon" variant="ghost" data-testid={\`button-edit-\${item.id}\`}>
                      <Edit className="w-4 h-4" />
                    </Button>
                  </Link>
                  <Button size="icon" variant="ghost" data-testid={\`button-delete-\${item.id}\`}>
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      
      {pagination && pagination.pages > 1 && (
        <div className="flex items-center justify-between p-3 border-t">
          <p className="text-sm text-muted-foreground">
            Showing {(pagination.page - 1) * pagination.limit + 1} to{' '}
            {Math.min(pagination.page * pagination.limit, pagination.total)} of{' '}
            {pagination.total} results
          </p>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={pagination.page <= 1}
              onClick={() => onPageChange?.(pagination.page - 1)}
              data-testid="button-prev-page"
            >
              Previous
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={pagination.page >= pagination.pages}
              onClick={() => onPageChange?.(pagination.page + 1)}
              data-testid="button-next-page"
            >
              Next
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
`;
    
    return {
      path: `generated/${blueprintId}/client/src/components/${this.toKebabCase(entity.name)}-table.tsx`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Generate entity form component
   */
  private generateEntityForm(entity: EntityDefinition, blueprintId: string): GeneratedFile {
    const formFields = entity.fields.filter(f => 
      !['id', 'createdAt', 'updatedAt', 'deletedAt', 'tenantId'].includes(f.name)
    );
    
    const defaultValues = formFields.map(f => 
      `      ${f.name}: defaultValues?.${f.name} || ${this.getDefaultValue(f)}`
    ).join(',\n');
    
    const formFieldsJsx = formFields.map(f => this.generateFormField(f)).join('\n\n');
    
    const content = `/**
 * ${entity.name} Form Component - نموذج ${entity.nameAr}
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { insert${entity.name}Schema } from '@shared/types';
import { Save, Loader2 } from 'lucide-react';

interface ${entity.name}FormProps {
  defaultValues?: any;
  loading?: boolean;
  onSubmit: (data: any) => void;
}

export function ${entity.name}Form({ defaultValues, loading, onSubmit }: ${entity.name}FormProps) {
  const form = useForm({
    resolver: zodResolver(insert${entity.name}Schema),
    defaultValues: {
${defaultValues}
    }
  });

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
${formFieldsJsx}
        
        <div className="flex items-center gap-2 pt-4">
          <Button type="submit" disabled={loading} data-testid="button-submit">
            {loading ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Save className="w-4 h-4 mr-2" />
            )}
            Save
          </Button>
        </div>
      </form>
    </Form>
  );
}
`;
    
    return {
      path: `generated/${blueprintId}/client/src/components/${this.toKebabCase(entity.name)}-form.tsx`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Generate form field JSX based on field type
   */
  private generateFormField(field: FieldDefinition): string {
    const label = field.nameAr;
    const name = field.name;
    
    switch (field.type) {
      case 'boolean':
        return `        <FormField
          control={form.control}
          name="${name}"
          render={({ field }) => (
            <FormItem className="flex items-center justify-between">
              <FormLabel>${label}</FormLabel>
              <FormControl>
                <Switch
                  checked={field.value}
                  onCheckedChange={field.onChange}
                  data-testid="switch-${name}"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />`;
      
      case 'text':
        return `        <FormField
          control={form.control}
          name="${name}"
          render={({ field }) => (
            <FormItem>
              <FormLabel>${label}</FormLabel>
              <FormControl>
                <Textarea {...field} data-testid="input-${name}" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />`;
      
      case 'integer':
      case 'bigint':
      case 'decimal':
        return `        <FormField
          control={form.control}
          name="${name}"
          render={({ field }) => (
            <FormItem>
              <FormLabel>${label}</FormLabel>
              <FormControl>
                <Input type="number" {...field} data-testid="input-${name}" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />`;
      
      case 'date':
      case 'datetime':
      case 'timestamp':
        return `        <FormField
          control={form.control}
          name="${name}"
          render={({ field }) => (
            <FormItem>
              <FormLabel>${label}</FormLabel>
              <FormControl>
                <Input type="datetime-local" {...field} data-testid="input-${name}" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />`;
      
      default:
        return `        <FormField
          control={form.control}
          name="${name}"
          render={({ field }) => (
            <FormItem>
              <FormLabel>${label}</FormLabel>
              <FormControl>
                <Input {...field} data-testid="input-${name}" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />`;
    }
  }
  
  /**
   * Get default value for a field type
   */
  private getDefaultValue(field: FieldDefinition): string {
    if (field.defaultValue !== undefined) {
      if (typeof field.defaultValue === 'string') return `'${field.defaultValue}'`;
      return String(field.defaultValue);
    }
    
    switch (field.type) {
      case 'boolean': return 'false';
      case 'integer':
      case 'bigint':
      case 'decimal': return '0';
      case 'array': return '[]';
      case 'json':
      case 'jsonb': return '{}';
      default: return "''";
    }
  }
  
  /**
   * Generate sidebar component
   */
  private generateSidebar(navigation: NavigationSpec, blueprintId: string): GeneratedFile {
    const items = navigation.items.map(item => `
    {
      title: '${item.label}',
      titleAr: '${item.labelAr}',
      url: '${item.path}',
      icon: ${item.icon}
    }`).join(',');
    
    const content = `/**
 * App Sidebar - الشريط الجانبي
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

import { useLocation, Link } from 'wouter';
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarHeader,
  SidebarFooter
} from '@/components/ui/sidebar';
import { LayoutDashboard, Database, Settings, Users, FileText, Package } from 'lucide-react';

const navItems = [${items}
];

export function AppSidebar() {
  const [location] = useLocation();

  return (
    <Sidebar>
      <SidebarHeader className="p-4 border-b">
        <h2 className="text-lg font-bold">Platform</h2>
      </SidebarHeader>
      
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel>Navigation</SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>
              {navItems.map((item) => (
                <SidebarMenuItem key={item.url}>
                  <SidebarMenuButton 
                    asChild 
                    isActive={location === item.url}
                    data-testid={\`nav-\${item.url.replace(/\\//g, '-').slice(1) || 'home'}\`}
                  >
                    <Link href={item.url}>
                      <item.icon className="w-4 h-4" />
                      <span>{item.titleAr}</span>
                    </Link>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      
      <SidebarFooter className="p-4 border-t">
        <p className="text-xs text-muted-foreground">Generated by INFERA</p>
      </SidebarFooter>
    </Sidebar>
  );
}
`;
    
    return {
      path: `generated/${blueprintId}/client/src/components/app-sidebar.tsx`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Generate theme CSS variables
   */
  private generateThemeCSS(theme: ThemeSpec, blueprintId: string): GeneratedFile {
    const content = `/**
 * Theme CSS Variables
 * Generated by Blueprint Compiler
 * Blueprint ID: ${blueprintId}
 */

:root {
  --primary: ${this.hexToHSL(theme.primaryColor)};
  --accent: ${this.hexToHSL(theme.accentColor)};
  
  --font-latin: '${theme.fonts.latin}', system-ui, sans-serif;
  --font-arabic: '${theme.fonts.arabic}', system-ui, sans-serif;
}

${theme.rtlSupport ? `
[dir="rtl"] {
  font-family: var(--font-arabic);
}

[dir="ltr"] {
  font-family: var(--font-latin);
}
` : ''}
`;
    
    return {
      path: `generated/${blueprintId}/client/src/theme.css`,
      content,
      type: 'typescript',
      checksum: this.generateChecksum(content),
      generatedAt: new Date()
    };
  }
  
  /**
   * Convert hex color to HSL format
   */
  private hexToHSL(hex: string): string {
    // Remove # if present
    hex = hex.replace('#', '');
    
    const r = parseInt(hex.substring(0, 2), 16) / 255;
    const g = parseInt(hex.substring(2, 4), 16) / 255;
    const b = parseInt(hex.substring(4, 6), 16) / 255;
    
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    let h = 0, s = 0;
    const l = (max + min) / 2;
    
    if (max !== min) {
      const d = max - min;
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
      
      switch (max) {
        case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
        case g: h = ((b - r) / d + 2) / 6; break;
        case b: h = ((r - g) / d + 4) / 6; break;
      }
    }
    
    return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
  }
  
  /**
   * Convert string to kebab-case
   */
  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }
  
  /**
   * Generate simple checksum
   */
  private generateChecksum(content: string): string {
    let hash = 0;
    for (let i = 0; i < content.length; i++) {
      const char = content.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(16);
  }
}

export const frontendGenerator = new FrontendGenerator();
