# INFERA WebNova - Secrets Management Guide
# ============================================
# DO NOT store actual secrets in this file or any YAML file.
# Use one of the following secure methods:

# OPTION 1: Sealed Secrets (Recommended for GitOps)
# -------------------------------------------------
# 1. Install sealed-secrets controller
# 2. Create a SealedSecret from your secret:
#    kubeseal --format yaml < my-secret.yaml > sealed-secret.yaml
# 3. Commit only the sealed-secret.yaml

# OPTION 2: External Secrets Operator
# -----------------------------------
# 1. Install external-secrets operator
# 2. Configure SecretStore for your provider (AWS, GCP, Azure, Vault)
# 3. Create ExternalSecret resources that sync secrets

# OPTION 3: SOPS with Age/GPG
# ---------------------------
# 1. Install sops: https://github.com/getsops/sops
# 2. Encrypt secrets: sops -e secrets.yaml > secrets.enc.yaml
# 3. Decrypt at deploy time: sops -d secrets.enc.yaml | kubectl apply -f -

# OPTION 4: HashiCorp Vault
# -------------------------
# 1. Deploy Vault in your cluster
# 2. Use Vault Agent Injector for pod secret injection
# 3. Secrets are injected at runtime, never stored in YAML

# Example ExternalSecret (for External Secrets Operator):
# -------------------------------------------------------
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: infera-secrets
#   namespace: infera
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend
#     kind: SecretStore
#   target:
#     name: infera-secrets
#   data:
#     - secretKey: DATABASE_URL
#       remoteRef:
#         key: infera/database
#         property: url
#     - secretKey: ANTHROPIC_API_KEY
#       remoteRef:
#         key: infera/ai
#         property: anthropic_key

---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: infera-config
  namespace: infera
  labels:
    app: infera-webnova
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  HOST: "0.0.0.0"
  PORT: "5000"
  DB_POOL_MIN: "2"
  DB_POOL_MAX: "10"
  ENABLE_DOCKER_ISOLATION: "true"
  ENABLE_AI_FEATURES: "true"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"
